@startuml
'https://plantuml.com/sequence-diagram

ATMS -> ActivityStarter : executeRequest
ActivityStarter -> ActivityStarter :startActivityUnchecked
ActivityStarter -> ActivityStarter:startActivityInner
ActivityStarter -> RootWindowContainer :resumeFocusedTasksTopActivities
RootWindowContainer -> Task : resumeTopActivityUncheckedLocked
Task -> TaskFragment: resumeTopActivity
TaskFragment -> TaskDisplayArea: pauseBackTasks
TaskFragment ->ATMS: startProcessAsync
TaskFragment -> TaskFragment:completePause
note left : Launcher暂停完成
TaskFragment -> RootWindowContainer: resumeFocusedTasksTopActivities
RootWindowContainer -> Task : resumeTopActivityUncheckedLocked
Task -> TaskFragment: resumeTopActivity
TaskFragment -> TaskDisplayArea : ensureActivitiesVisible
note left: 重新设置所有 Activity的可见性，Launcher被置为 false
TaskFragment -> ActivityRecord : setVisibility
note left : 将应用 Activity置为可见
TaskFragment -> ActivityTaskSupervisor:startSpecificActivity
ActivityTaskSupervisor -> ATMS:startProcessAsync
note left : 进程如果依然不存在
ActivityThread -> ActivityThread: main
ActivityThread -> ActivityThread:attach
ActivityThread -> AMS: attachApplication
AMS -> AMS :attachApplicationLocked
AMS -> ActivityThread: bindApplication
note left : 创建 Application
AMS -> ATMS: attachApplication
ATMS -> RootWindowContainer: attachApplication
RootWindowContainer -> ActivityTaskSupervisor:realStartActivityLocked
ActivityTaskSupervisor -> ActivityTaskSupervisor: tryRealStartActivityInner
ActivityTaskSupervisor -> ActivityRecord: setState
ActivityRecord -> TaskFragment: onActivityStateChanged
TaskFragment -> TaskFragment: setResumedActivity
TaskFragment -> ATMS : setLastResumedActivityUncheckLocked
ATMS -> DisPlayContent : setFocusedApp
note left : 更新焦点应用
DisPlayContent -> InputMonitor:setFocusedAppLw
note left: 通知 SFlinger 更新焦点窗口
ATMS -> WMS: updateFocusedWindowLocked
WMS -> RootWindowContainer:updateFocusedWindowLocked
RootWindowContainer -> DisPlayContent: updateFocusedWindowLocked
note right : Changing focus 更新焦点窗口，当前应用还未启动 ,焦点窗口为空
VRI ->WMS : relayoutWindow
WMS -> WMS: updateFocusedWindowLocked
WMS -> RootWindowContainer: updateFocusedWindowLocked
RootWindowContainer -> DisPlayContent: updateFocusedWindowLocked
note right : Changing focus 更新焦点窗口，窗口已准备就绪

DisPlayContent -> InputMonitor: setInputFocusLw
@enduml