@startuml
'https://plantuml.com/sequence-diagram
QuickStepLauncher -> ActivityContext:startActivitySafely
ActivityContext -> QuickstepTransitionManager:getActivityLaunchOptions
QuickStepLauncher -> Instrumentation:execStartActivity
Instrumentation -> ATMS:startActivity
ATMS -> ActivityStarter : executeRequest
note left: 构造ActivityRecord
ActivityStarter -> TransitionController: createAndStartCollecting
TransitionController -> TransitionController: moveToCollecting
TransitionController -> Transition: startCollecting
note right : mState = STATE_COLLECTING;
Transition -> BLASTSyncEngine: startSyncSet
BLASTSyncEngine -> BLASTSyncEngine: prepareSyncSet
ActivityStarter -> ActivityStarter:startActivityUnchecked
ActivityStarter -> TransitionController:collect
note left: 收集当前ActivityRecord
TransitionController -> Transition:collect
ActivityStarter -> ActivityStarter: startActivityInner
note left: 新建Task
ActivityStarter -> Task : startActivityLocked
note left: 将StartingWindow加入到当前ActivityRecord中
ActivityStarter -> ActivityStarter: handleStartResult
ActivityStarter -> TransitionController:requestStartTransition
TransitionController -> TransitionPlayerImpl:requestStartTransition
TransitionPlayerImpl -> Transitions: requestStartTransition
Transitions -> Transitions:dispatchRequestWithTracing
Transitions -> Transitions:dispatchRequest
Transitions -> DefaultMixedHandler:handleRequest
DefaultMixedHandler -> Transitions:dispatchRequest
Transitions -> RemoteTransitionHandler: handleRequest
Transitions -> ShellTaskOrganizer:startTransition
ShellTaskOrganizer -> WindowOrganizerController:startTransition
WindowOrganizerController -> Transition:start
note left : mState = STATE_STARTED
Transition -> Transition:applyReady
BLASTSyncEngine -> BLASTSyncEngine:onSurfacePlacement
BLASTSyncEngine -> SyncGroup:tryFinish
SyncGroup -> SyncGroup:finishNow
SyncGroup -> Transition:onTransactionReady
note left:mState = STATE_PLAYING
Transition -> Transition:calculateTargets
Transition -> Transition:calculateTransitionInfo
note left:change的数量？
Transition -> Transition:calculateTransitionRoots
note left: 新建leashRoot，将参与动画的Task挂载到此leash下
Transition -> Transition: buildFinishTransaction
note left: 构造finishTransaction 恢复原先的Task结构
Transition -> TransitionPlayerImpl:onTransitionReady
TransitionPlayerImpl -> Transitions:onTransitionReady
Transitions -> Transitions:dispatchReady
Transitions -> Transitions: setupStartState
note left: 设置leash状态:start 显示对应应用/finish隐藏 Home
Transitions -> Transitions:processReadyQueue
Transitions -> Transitions:playTransitionWithTracing
Transitions -> Transitions:playTransition
Transitions -> Transitions: setupAnimHierarchy
note left : 设置 layer z轴层级:启动应用>Home
Transitions -> DefaultMixedHandler:startAnimation
DefaultMixedHandler -> DefaultMixedTransition:startAnimation
DefaultMixedTransition -> DefaultMixedTransition:animateOpenIntentWithRemoteAndPipOrDesktop
DefaultMixedTransition -> DefaultMixedTransition:tryAnimateOpenIntentWithRemoteAndPipOrDesktop
DefaultMixedTransition -> RemoteTransitionHandler:startAnimation
RemoteTransitionHandler -> RemoteTransition:getRemoteTransition
RemoteTransition -> IRemoteTransition: startAnimation
IRemoteTransition -> RemoteTransitionStub:startAnimation
RemoteTransitionStub -> LauncherAnimationRunner: onAnimationStart
LauncherAnimationRunner -> QuickstepTransitionManager:composeIconLaunchAnimator
@enduml